GET http://localhost:3001/api/products HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/products/new HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/products/all HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/products/147 HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/products HTTP/1.1
content-type: application/json

{
  "name": "Producto de prueba",
  "description": "Descripción de prueba",
  "price": 10.99,
  "brand": "TestBrand",
  "stock": 5,
  "images": ["/images/product/test.jpg"],
  "categoryId": 1,
  "subcategoryId": 1
}

###
DELETE http://localhost:3001/api/products/1 HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/categories HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/categories/featured HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/categories/77 HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/categories HTTP/1.1
content-type: application/json

{
  "name": "Nueva categoría",
  "image": "/images/categories/test.png",
  "description": "Descripción de prueba",
  "featured": false,
  "subcategories": ["Subcat1", "Subcat2"]
}

###
PUT http://localhost:3001/api/categories/1/featured HTTP/1.1
content-type: application/json

{
  "featured": true
}

###
GET http://localhost:3001/api/users HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/users/1 HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/users/search?email=ana@correo.com HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "test@example.com",
  "password": "123456",
  "role": "cliente"
}

###
DELETE http://localhost:3001/api/users/1 HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

###
GET http://localhost:3001/api/orders HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/orders/104 HTTP/1.1
content-type: application/json

